# Generated by Django 5.1 on 2024-08-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_video_url_video_video_file_alter_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='caption',
        ),
    ]
