# Generated by Django 5.1 on 2024-08-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tour_end_time_tour_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='location_address',
        ),
        migrations.AddField(
            model_name='tour',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
