# Generated by Django 5.1 on 2024-08-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_tour_latitude_remove_tour_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='location_address',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_time',
        ),
    ]
