# Generated by Django 5.1 on 2024-08-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_tour_end_time_tour_location_tour_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
