# Generated by Django 5.1 on 2024-09-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_aboutus_authentic_experiences_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_time',
        ),
    ]
